services:
  pg-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=ny_taxi 
    volumes:
      - ./ny_taxi/data:/var/lib/postgresql/data:rw
    ports:
      - 7001:7001
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80 